### ISSUE TITLE
Dead link?

### ISSUE THREAD

**Issue by 109C** [franklin-lb/franklin-lb.github.io#1]
There isn't anything at [franklin-lb.github.io](https://franklin-lb.github.io/).

**Comment by bjskistad** [comment]
Idk what's wrong. I'll try remaking the repo.

**Comment by bjskistad** [comment]
New repo works!

**Comment by 109C** [comment]
Not dead anymore :+1:

**Comment by bjskistad** [comment]
Just wondering, do you know Python? I'm looking for some Python devs.

**Comment by 109C** [comment]
I know a little bit of python, I've done some python. I should be able to help with any python projects.

**Comment by bjskistad** [comment]
OK! I'm creating a programming language called Jel, which is JavaScript in Python form.
